# This is a basic workflow to help you get started with Actions

name: Monitor

on:
  schedule:
    - cron: '*/5 * * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  monitor:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      - name: Check if bat24 page is up
        run: curl -sSf https://begvog.github.io/bat24_workshop/
